import { BaseSchema } from '@adonisjs/lucid/schema'

/**
 * A turn is now recorded the moment it is submitted, before it is played, and
 * a repeated submission finds it there instead of playing a second turn.
 */
export default class extends BaseSchema {
  protected tableName = 'turn_log'

  async up() {
    this.schema.alterTable(this.tableName, (table) => {
      /**
       * Generated by the client, one per submission. Nullable only for the
       * rows written before it existed: every new turn carries one.
       */
      table.uuid('idempotency_key').nullable()

      /**
       * Per game, not global: the key only has to tell apart the submissions
       * of one game, and this is also the lookup a repeated submission makes.
       */
      table.unique(['session_id', 'idempotency_key'])

      /**
       * A turn only gets its number once it has completed: a pending turn has
       * not earned its place in the story yet, and a failed one never will.
       */
      table.setNullable('turn_number')
    })

    /**
     * Failed rows written before this migration held a number. Released, so
     * the invariant below holds for every row.
     */
    this.defer(async (db) => {
      await db.rawQuery(`UPDATE turn_log SET turn_number = NULL WHERE status <> 'completed'`)
    })

    this.schema.alterTable(this.tableName, (table) => {
      table.check(
        `(status = 'completed') = (turn_number IS NOT NULL)`,
        [],
        'turn_log_number_matches_status'
      )
    })
  }

  async down() {
    this.schema.alterTable(this.tableName, (table) => {
      table.dropChecks('turn_log_number_matches_status')
    })

    /**
     * The previous schema has no room for a turn without a number. Those rows
     * are pending or failed — never part of the story — and go.
     */
    this.defer(async (db) => {
      await db.rawQuery('DELETE FROM turn_log WHERE turn_number IS NULL')
    })

    this.schema.alterTable(this.tableName, (table) => {
      table.dropNullable('turn_number')
      table.dropUnique(['session_id', 'idempotency_key'])
      table.dropColumn('idempotency_key')
    })
  }
}
