/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CharacterSchema extends BaseModel {
  static $columns = ['attributes', 'createdAt', 'hitPoints', 'hitPointsMax', 'id', 'name', 'progression', 'resources', 'sessionId', 'skills', 'updatedAt'] as const
  $columns = CharacterSchema.$columns
  @column()
  declare attributes: any
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare hitPoints: number
  @column()
  declare hitPointsMax: number
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare progression: any
  @column()
  declare resources: any
  @column()
  declare sessionId: string
  @column()
  declare skills: any
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SessionSchema extends BaseModel {
  static $columns = ['createdAt', 'currentChapter', 'id', 'lastActivityAt', 'status', 'userId'] as const
  $columns = SessionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currentChapter: string | null
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare lastActivityAt: DateTime
  @column()
  declare status: 'in_progress' | 'paused' | 'completed'
  @column()
  declare userId: string
}

export class TurnLogSchema extends BaseModel {
  static $columns = ['alerts', 'appliedEffects', 'arbitrationOutput', 'createdAt', 'id', 'llmUsage', 'narratedText', 'playerInput', 'rollResult', 'sessionId', 'turnNumber'] as const
  $columns = TurnLogSchema.$columns
  @column()
  declare alerts: any | null
  @column()
  declare appliedEffects: any | null
  @column()
  declare arbitrationOutput: any | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare llmUsage: any | null
  @column()
  declare narratedText: string | null
  @column()
  declare playerInput: string
  @column()
  declare rollResult: any | null
  @column()
  declare sessionId: string
  @column()
  declare turnNumber: number
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'role', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: string
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare role: 'player' | 'game_master' | 'superadmin'
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class WorldStateSchema extends BaseModel {
  static $columns = ['activeQuests', 'createdAt', 'id', 'narrativeFlags', 'sessionId', 'updatedAt', 'visitedLocations', 'worldObjects'] as const
  $columns = WorldStateSchema.$columns
  @column()
  declare activeQuests: any
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare narrativeFlags: any
  @column()
  declare sessionId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare visitedLocations: any
  @column()
  declare worldObjects: any
}
