import { DateTime } from 'luxon'
import db from '@adonisjs/lucid/services/db'
import type { TransactionClientContract } from '@adonisjs/lucid/types/database'

import TurnLog from '#models/turn_log'
import { describeTurnFailure } from '#exceptions/turn_failure'
import Session from '#models/session'
import type Character from '#models/character'
import type WorldState from '#models/world_state'
import type { LlmGateway } from '#services/llm/gateway'
import type { LlmCallMetadata } from '#services/llm/types'
import type { RulesEngine } from '#services/rules/engine'
import type { JobQueue } from '#services/queue/types'
import { toNarrationOutcome } from '#services/rules/engine'
import type { RollResolution } from '#services/rules/types'

import {
  ConcurrentTurnError,
  QueueUnavailableError,
  StaleTurnError,
  isTurnNumberConflict,
} from './errors.js'
import { THREE_MUSKETEERS, locationReferences } from './world.js'
import {
  ARBITRATION_SCHEMA,
  ARBITRATION_SYSTEM_PROMPT,
  buildArbitrationMessage,
} from './prompts/arbitration.js'
import {
  NARRATION_SCHEMA,
  NARRATION_SYSTEM_PROMPT,
  buildNarrationMessage,
} from './prompts/narration.js'
import type {
  ArbitrationOutput,
  GameLanguage,
  RecentTurn,
  TurnContext,
  TurnEffects,
} from './prompts/types.js'
import { type ValidationMeta, validateArbitration, validateNarration } from './turn_validator.js'

/**
 * How many past turns travel to the model as the recent buffer.
 *
 * Re-sent in full on every turn, so it is the dominant cost driver of a long
 * session. The long-term memory that would let it stay small is Phase 7.
 */
const RECENT_TURNS = 5

/**
 * Phase 1 plays in English. Still passed explicitly at every step rather than
 * hardcoded downstream: the architecture document requires the language to
 * never be assumed fixed.
 */
export const DEFAULT_LANGUAGE: GameLanguage = 'en'

/** The queue turns are played from, one job per turn. */
export const PLAY_TURN_QUEUE = 'play-turn'

/** The job carries the turn's id and nothing else: all state is read from the database. */
export type PlayTurnJob = {
  turnId: string
}

/**
 * What a turn left pending too long is marked with. Its message is the one the
 * player reads back.
 */
const EXPIRED: StoredFailure = {
  code: 'turn_expired',
  message: 'The game master never finished this turn. Try your action again.',
}

export type TurnSubmission = {
  sessionId: string
  /**
   * Whose session it is. The lookup is scoped to it rather than checked
   * afterwards, so someone else's session reads as one that does not exist.
   */
  userId: string
  playerInput: string
  /**
   * Generated by the client, one per submission — not per text. Sending the
   * same submission again (double click, network lost before the answer) reuses
   * it; a retry after a failed turn is a new submission with a new key.
   */
  idempotencyKey: string
  language?: GameLanguage
}

export type SubmittedTurn = {
  turn: TurnLog
  /**
   * The key was already known: the turn it names is returned as it stands, and
   * nothing is played a second time.
   */
  replayed: boolean
}

/**
 * One turn, end to end.
 *
 * Split in two on purpose: `submit` records the turn and queues it, answering
 * the player at once; `run` plays it, in a job. Regenerating the narrative
 * summary is Phase 7.
 */
export class TurnService {
  #llm: LlmGateway
  #rules: RulesEngine
  #queue: JobQueue

  constructor(llm: LlmGateway, rules: RulesEngine, queue: JobQueue) {
    this.#llm = llm
    this.#rules = rules
    this.#queue = queue
  }

  /**
   * Records the submission and queues it — unless its key is already known, in
   * which case the existing turn is returned and nothing is queued again.
   *
   * Enqueued after the turn is written, never in the same transaction: BullMQ
   * could not take part in one. A turn that cannot be queued is marked failed
   * at once, since no job will ever pick it up.
   */
  async submit(submission: TurnSubmission): Promise<SubmittedTurn> {
    const recorded = await this.record(submission)

    if (recorded.replayed) {
      return recorded
    }

    try {
      await this.#queue.enqueue<PlayTurnJob>(PLAY_TURN_QUEUE, { turnId: recorded.turn.id })
    } catch (cause) {
      const error = new QueueUnavailableError({ cause })

      await markFailed(recorded.turn.id, emptyTrace(), error)

      throw error
    }

    return recorded
  }

  /**
   * Fails every turn still pending since before `cutoff`: its process died
   * mid-turn, or its job was lost. Left alone, it would keep the game screen
   * waiting on a turn nothing will ever finish.
   *
   * Returns the ids it expired.
   */
  async expireStale(cutoff: DateTime): Promise<string[]> {
    const rows: { id: string }[] = await db
      .from('turn_log')
      .where('status', 'pending')
      .where('created_at', '<', cutoff.toJSDate())
      .update({ status: 'failed', failure: EXPIRED })
      .returning('id')

    return rows.map((row) => row.id)
  }

  /**
   * Records a submitted turn as pending, before anything is played: recording
   * it only at the end would let a repeated submission through for the whole
   * time the model takes to answer.
   */
  async record(submission: TurnSubmission): Promise<SubmittedTurn> {
    const session = await Session.query()
      .where('id', submission.sessionId)
      .where('userId', submission.userId)
      .firstOrFail()

    /**
     * `ON CONFLICT DO NOTHING` rather than catching the unique violation: in
     * PostgreSQL a failed insert aborts the surrounding transaction, and the
     * lookup that follows would fail with it.
     */
    const [inserted] = await db
      .table('turn_log')
      .insert({
        session_id: session.id,
        idempotency_key: submission.idempotencyKey,
        status: 'pending',
        player_input: submission.playerInput,
        language: submission.language ?? DEFAULT_LANGUAGE,
        created_at: new Date(),
      })
      .onConflict(['session_id', 'idempotency_key'])
      .ignore()
      .returning('id')

    if (inserted) {
      return { turn: await TurnLog.findOrFail(inserted.id), replayed: false }
    }

    const existing = await TurnLog.query()
      .where('sessionId', session.id)
      .where('idempotencyKey', submission.idempotencyKey)
      .firstOrFail()

    return { turn: existing, replayed: true }
  }

  /**
   * Plays a pending turn. Takes only its id and reads everything else from the
   * database, which is all a queued job will carry.
   */
  async run(turnId: string): Promise<TurnLog> {
    const turn = await TurnLog.findOrFail(turnId)

    if (turn.status !== 'pending') {
      throw new Error(`Turn ${turnId} is ${turn.status}: only a pending turn can be played.`)
    }

    const scene = await this.#loadScene(turn.sessionId)

    /**
     * Filled as the pipeline progresses, so a turn that dies halfway still
     * leaves behind everything it had managed to produce.
     */
    const trace = emptyTrace()

    try {
      const effects = await this.#runPipeline(turn, scene, trace)

      await this.#complete(turn, scene, trace, effects)

      return turn
    } catch (error) {
      /**
       * The log of a failed turn is what makes the failure debuggable at all,
       * so it is written before the error is re-thrown — and its own failure is
       * swallowed rather than allowed to mask the real one.
       */
      await markFailed(turn.id, trace, error).catch(() => {})

      throw error
    }
  }

  /** Returns the effects the model proposed, validated but not yet applied. */
  async #runPipeline(turn: TurnLog, scene: LoadedScene, trace: TurnTrace): Promise<TurnEffects> {
    const context = buildContext(scene, turn.playerInput, turn.language)
    const meta: ValidationMeta = {
      skills: Object.keys(scene.character.skills),
      locations: locationReferences(THREE_MUSKETEERS),
      hitPointsMax: scene.character.hitPointsMax,
    }

    const arbitration = await this.#llm.generateJson<unknown>('arbitration', {
      systemPrompt: ARBITRATION_SYSTEM_PROMPT,
      userMessage: buildArbitrationMessage(context),
      jsonSchema: ARBITRATION_SCHEMA as unknown as Record<string, unknown>,
    })

    trace.usage.push(arbitration.metadata)

    const decision = await validateArbitration(arbitration.content, meta)
    trace.arbitration = decision

    /**
     * No roll: arbitration already narrated and extracted, because the outcome
     * was settled the moment it ruled. One call, and the turn is done.
     */
    if (decision.resolution.mode !== 'roll_required') {
      trace.narration = decision.narration

      return decision.effects as TurnEffects
    }

    const resolution = this.#rules.resolve(
      scene.character.skills[decision.resolution.skill_used as string],
      decision.resolution.difficulty!
    )

    trace.roll = resolution

    const narration = await this.#llm.generateJson<unknown>('narration', {
      systemPrompt: NARRATION_SYSTEM_PROMPT,
      userMessage: buildNarrationMessage({
        ...context,
        /** A verdict and a qualitative margin. Never the dice or the threshold. */
        outcome: toNarrationOutcome(resolution),
        intent_summary: decision.intent.summary,
      }),
      jsonSchema: NARRATION_SCHEMA as unknown as Record<string, unknown>,
    })

    trace.usage.push(narration.metadata)

    const narrated = await validateNarration(narration.content, meta)
    trace.narration = narrated.narration

    return narrated.effects
  }

  /**
   * Ownership was checked when the turn was recorded: from here on, the turn
   * is all there is to go on.
   */
  async #loadScene(sessionId: string): Promise<LoadedScene> {
    const session = await Session.query()
      .where('id', sessionId)
      .preload('characters')
      .preload('worldState')
      .firstOrFail()

    const character = session.characters[0]

    if (!character) {
      throw new Error(`Session ${sessionId} has no character to play.`)
    }

    /**
     * Completed turns only: a failed turn is not part of the story, and handing
     * the model an action that never happened would have it narrate around it.
     */
    const turns = await TurnLog.query()
      .where('sessionId', sessionId)
      .withScopes((scopes) => scopes.completed())
      .orderBy('turnNumber', 'desc')
      .limit(RECENT_TURNS)

    /** Only completed turns hold a number, so the highest one is the last of the story. */
    const last = await TurnLog.query()
      .where('sessionId', sessionId)
      .max('turn_number as max')
      .first()

    return {
      session,
      character,
      worldState: session.worldState,
      /** Oldest first, so the model reads the exchange in the order it happened. */
      recentTurns: turns.reverse(),
      lastTurnNumber: Number(last?.$extras.max ?? 0),
    }
  }

  /**
   * State change and turn log land together: a state that moved without a log
   * entry explaining it would be impossible to reconstruct afterwards.
   *
   * The turn gets its number here, and only here: a number is a place in the
   * story, which a turn earns by completing.
   */
  async #complete(
    turn: TurnLog,
    scene: LoadedScene,
    trace: TurnTrace,
    effects: TurnEffects
  ): Promise<void> {
    const turnNumber = scene.lastTurnNumber + 1

    try {
      await db.transaction(async (trx) => {
        /**
         * Locked and re-read: the sweep may have expired this turn while the
         * model was answering. Its outcome is then settled, and must not be
         * overwritten — nor its effects applied.
         */
        const current = await TurnLog.query({ client: trx })
          .where('id', turn.id)
          .forUpdate()
          .firstOrFail()

        if (current.status !== 'pending') {
          throw new StaleTurnError(turn.id)
        }

        const applied = await applyEffects(scene, effects, trx)

        scene.session.lastActivityAt = DateTime.now()
        await scene.session.useTransaction(trx).save()

        turn.merge({
          ...traceColumns(trace),
          status: 'completed',
          turnNumber,
          /** As applied, which is what the player is shown — not as proposed. */
          appliedEffects: applied,
        })

        await turn.useTransaction(trx).save()
      })
    } catch (error) {
      /**
       * Another request reached this turn number first. The transaction rolled
       * back, so nothing of this turn was applied.
       */
      if (isTurnNumberConflict(error)) {
        throw new ConcurrentTurnError(turnNumber)
      }

      throw error
    }
  }
}

type LoadedScene = {
  session: Session
  character: Character
  worldState: WorldState
  recentTurns: TurnLog[]
  lastTurnNumber: number
}

type TurnTrace = {
  arbitration: ArbitrationOutput | null
  roll: RollResolution | null
  narration: string | null
  usage: LlmCallMetadata[]
}

function buildContext(
  scene: LoadedScene,
  playerInput: string,
  language: GameLanguage
): TurnContext {
  return {
    world: THREE_MUSKETEERS,
    character: {
      name: scene.character.name,
      skills: scene.character.skills,
      hit_points: scene.character.hitPoints,
      hit_points_max: scene.character.hitPointsMax,
    },
    scene: {
      location: scene.worldState.currentLocation,
      narrative_flags: scene.worldState.narrativeFlags,
      visited_locations: scene.worldState.visitedLocations,
      world_objects: scene.worldState.worldObjects,
    },
    recent_buffer: toRecentBuffer(scene.recentTurns),
    player_input: playerInput,
    language,
  }
}

function toRecentBuffer(turns: TurnLog[]): RecentTurn[] {
  return turns.flatMap((turn) => {
    const entries: RecentTurn[] = [{ role: 'player', text: turn.playerInput }]

    if (turn.narratedText) {
      entries.push({ role: 'narration', text: turn.narratedText })
    }

    return entries
  })
}

/**
 * Applies the validated delta. Everything here is deterministic: the model
 * proposed, the backend decides what the numbers actually become.
 *
 * Returns what actually changed, which can be less than what was proposed: a
 * delta clamped at zero hit points, or a "movement" to where the character
 * already stands.
 */
async function applyEffects(
  scene: LoadedScene,
  effects: TurnEffects,
  trx: TransactionClientContract
): Promise<TurnEffects> {
  const { character, worldState } = scene
  const hitPointsBefore = character.hitPoints

  if (effects.hit_points_delta !== 0) {
    /**
     * Clamped rather than trusted: validation bounds the size of the swing, not
     * where it lands.
     */
    character.hitPoints = Math.max(
      0,
      Math.min(character.hitPointsMax, character.hitPoints + effects.hit_points_delta)
    )

    await character.useTransaction(trx).save()
  }

  const movement = effects.movement
  const moved = movement !== null && movement !== worldState.currentLocation

  if (moved) {
    worldState.visitedLocations = [...worldState.visitedLocations, { reference: movement }]
  }

  if (effects.scenario_flags.length > 0) {
    worldState.narrativeFlags = {
      ...worldState.narrativeFlags,
      ...Object.fromEntries(effects.scenario_flags.map((flag) => [flag, true])),
    }
  }

  if (moved || effects.scenario_flags.length > 0) {
    await worldState.useTransaction(trx).save()
  }

  return {
    movement: moved ? movement : null,
    scenario_flags: effects.scenario_flags,
    hit_points_delta: character.hitPoints - hitPointsBefore,
  }
}

/**
 * Marks a turn failed, with whatever the pipeline had produced and why it
 * stopped. Read afresh: the instance that failed may still be bound to the
 * transaction that rolled back.
 */
async function markFailed(turnId: string, trace: TurnTrace, error: unknown): Promise<void> {
  const turn = await TurnLog.findOrFail(turnId)

  /** Already settled — by the sweep, most likely. The first outcome stands. */
  if (turn.status !== 'pending') {
    return
  }

  turn.merge({
    ...traceColumns(trace),
    status: 'failed',
    /** A failed turn never takes a place in the story. */
    turnNumber: null,
    appliedEffects: null,
    failure: toStoredFailure(error),
  })

  await turn.save()
}

function emptyTrace(): TurnTrace {
  return { arbitration: null, roll: null, narration: null, usage: [] }
}

function traceColumns(trace: TurnTrace) {
  return {
    arbitrationOutput: trace.arbitration as Record<string, unknown> | null,
    rollResult: trace.roll as Record<string, unknown> | null,
    narratedText: trace.narration,
    alerts: toAlerts(trace.arbitration),
    /**
     * Both calls of a turn are recorded, so the real cost of a turn is the sum
     * of what it actually spent — including the arbitration of a turn that then
     * failed in narration.
     */
    llmUsage: trace.usage.map(toUsageRow),
  }
}

/**
 * What the player was told, kept so that reading the turn back tells them the
 * same thing. The step and the rejected rules are for whoever debugs it.
 */
type StoredFailure = {
  code: string
  message: string
  step?: string
  reasons?: { field: string; rule: string; message: string }[]
}

function toStoredFailure(error: unknown): StoredFailure {
  const failure = describeTurnFailure(error)

  if (!failure) {
    return { code: 'unexpected_error', message: 'Something went wrong while playing this turn.' }
  }

  const { status, ...stored } = failure

  return stored
}

function toAlerts(arbitration: ArbitrationOutput | null): Record<string, unknown>[] | null {
  if (!arbitration) {
    return null
  }

  const raised = Object.entries(arbitration.alert)
    .filter(([, value]) => value === true)
    .map(([kind]) => ({ kind }))

  return raised.length > 0 ? raised : null
}

function toUsageRow(metadata: LlmCallMetadata): Record<string, unknown> {
  return {
    step: metadata.step,
    provider: metadata.provider,
    model: metadata.model,
    input_tokens: metadata.usage.inputTokens,
    output_tokens: metadata.usage.outputTokens,
    reasoning_tokens: metadata.usage.reasoningTokens,
    total_tokens: metadata.usage.totalTokens,
    duration_ms: metadata.durationMs,
  }
}
