import { DateTime } from 'luxon'
import db from '@adonisjs/lucid/services/db'

import TurnLog from '#models/turn_log'
import Session from '#models/session'
import type Character from '#models/character'
import type WorldState from '#models/world_state'
import type { LlmGateway } from '#services/llm/gateway'
import type { RulesEngine } from '#services/rules/engine'
import type { Clock } from '#services/clock'
import type { JobQueue } from '#services/queue/types'
import type { TurnEvents, TurnRef } from '#services/game/turn_events'
import { toNarrationOutcome } from '#services/rules/engine'

import {
  ConcurrentTurnError,
  QueueUnavailableError,
  StaleTurnError,
  isTurnNumberConflict,
} from './errors.js'
import { applyDelta } from './apply_delta.js'
import { type PresentNpc, presentNpcs } from './npcs.js'
import { actionTypesOf, skillFor } from './resolution_rules.js'
import { TurnBudget } from './turn_budget.js'
import { callStructured } from './structured_call.js'
import {
  THREE_MUSKETEERS,
  locationArchetypeReferences,
  npcReferences,
  uniqueLocationReferences,
} from './world.js'
import {
  ARBITRATION_SCHEMA,
  ARBITRATION_SYSTEM_PROMPT,
  buildArbitrationMessage,
} from './prompts/arbitration.js'
import {
  NARRATION_RECENT_TURNS,
  NARRATION_SYSTEM_PROMPT,
  buildNarrationMessage,
} from './prompts/narration.js'
import {
  EXTRACTION_SCHEMA,
  EXTRACTION_SYSTEM_PROMPT,
  buildExtractionMessage,
} from './prompts/extraction.js'
import type {
  ArbitrationOutput,
  GameLanguage,
  OutcomeToNarrate,
  RecentTurn,
  TurnContext,
  TurnEffects,
} from './prompts/types.js'
import { type ValidationMeta, validateArbitration, validateExtraction } from './turn_validator.js'
import {
  type StoredFailure,
  type TurnTrace,
  emptyTrace,
  markFailed,
  recordCall,
  traceColumns,
} from './turn_trace.js'

/**
 * A skill missing from the character sheet is one they never learnt: rolled
 * at zero, so the dice alone carry the attempt.
 */
const UNTRAINED = 0

/**
 * Phase 1 plays in English. Still passed explicitly at every step rather than
 * hardcoded downstream: the architecture document requires the language to
 * never be assumed fixed.
 */
export const DEFAULT_LANGUAGE: GameLanguage = 'en'

/** The queue turns are played from, one job per turn. */
export const PLAY_TURN_QUEUE = 'play-turn'

/** The job carries the turn's id and nothing else: all state is read from the database. */
export type PlayTurnJob = {
  turnId: string
}

/**
 * What a turn left pending too long is marked with. Its message is the one the
 * player reads back.
 */
const EXPIRED: StoredFailure = {
  code: 'turn_expired',
  message: 'The game master never finished this turn. Try your action again.',
}

export type TurnSubmission = {
  sessionId: string
  /**
   * Whose session it is. The lookup is scoped to it rather than checked
   * afterwards, so someone else's session reads as one that does not exist.
   */
  userId: string
  playerInput: string
  /**
   * Generated by the client, one per submission — not per text. Sending the
   * same submission again (double click, network lost before the answer) reuses
   * it; a retry after a failed turn is a new submission with a new key.
   */
  idempotencyKey: string
  language?: GameLanguage
}

export type SubmittedTurn = {
  turn: TurnLog
  /**
   * The key was already known: the turn it names is returned as it stands, and
   * nothing is played a second time.
   */
  replayed: boolean
}

/**
 * One turn, end to end.
 *
 * Split in two on purpose: `submit` records the turn and queues it, answering
 * the player at once; `run` plays it, in a job. Regenerating the narrative
 * summary is Phase 7.
 */
export class TurnService {
  #llm: LlmGateway
  #rules: RulesEngine
  #queue: JobQueue
  #events: TurnEvents
  #clock: Clock

  constructor(
    llm: LlmGateway,
    rules: RulesEngine,
    queue: JobQueue,
    events: TurnEvents,
    clock: Clock
  ) {
    this.#llm = llm
    this.#rules = rules
    this.#queue = queue
    this.#events = events
    this.#clock = clock
  }

  /**
   * Records the submission and queues it — unless its key is already known, in
   * which case the existing turn is returned and nothing is queued again.
   *
   * Enqueued after the turn is written, never in the same transaction: BullMQ
   * could not take part in one. A turn that cannot be queued is marked failed
   * at once, since no job will ever pick it up.
   */
  async submit(submission: TurnSubmission): Promise<SubmittedTurn> {
    const recorded = await this.record(submission)

    if (recorded.replayed) {
      return recorded
    }

    try {
      await this.#queue.enqueue<PlayTurnJob>(PLAY_TURN_QUEUE, { turnId: recorded.turn.id })
    } catch (cause) {
      const error = new QueueUnavailableError({ cause })

      await this.#fail(recorded.turn, emptyTrace(), error)

      throw error
    }

    return recorded
  }

  /**
   * Fails every turn still pending since before `cutoff`: its process died
   * mid-turn, or its job was lost. Left alone, it would keep the game screen
   * waiting on a turn nothing will ever finish.
   *
   * Returns the ids it expired.
   */
  async expireStale(cutoff: DateTime): Promise<string[]> {
    const rows: { id: string; session_id: string; idempotency_key: string | null }[] = await db
      .from('turn_log')
      .where('status', 'pending')
      .where('created_at', '<', cutoff.toJSDate())
      .update({ status: 'failed', failure: EXPIRED })
      .returning(['id', 'session_id', 'idempotency_key'])

    /** A screen still waiting on one of these stops waiting now. */
    for (const row of rows) {
      this.#events.emit(
        { turnId: row.id, sessionId: row.session_id, idempotencyKey: row.idempotency_key },
        { type: 'turn_failed', failure: { code: EXPIRED.code, message: EXPIRED.message } }
      )
    }

    return rows.map((row) => row.id)
  }

  /**
   * Records a submitted turn as pending, before anything is played: recording
   * it only at the end would let a repeated submission through for the whole
   * time the model takes to answer.
   */
  async record(submission: TurnSubmission): Promise<SubmittedTurn> {
    const session = await Session.query()
      .where('id', submission.sessionId)
      .where('userId', submission.userId)
      .firstOrFail()

    /**
     * `ON CONFLICT DO NOTHING` rather than catching the unique violation: in
     * PostgreSQL a failed insert aborts the surrounding transaction, and the
     * lookup that follows would fail with it.
     */
    const [inserted] = await db
      .table('turn_log')
      .insert({
        session_id: session.id,
        idempotency_key: submission.idempotencyKey,
        status: 'pending',
        player_input: submission.playerInput,
        language: submission.language ?? DEFAULT_LANGUAGE,
        created_at: new Date(),
      })
      .onConflict(['session_id', 'idempotency_key'])
      .ignore()
      .returning('id')

    if (inserted) {
      return { turn: await TurnLog.findOrFail(inserted.id), replayed: false }
    }

    const existing = await TurnLog.query()
      .where('sessionId', session.id)
      .where('idempotencyKey', submission.idempotencyKey)
      .firstOrFail()

    return { turn: existing, replayed: true }
  }

  /**
   * Plays a pending turn. Takes only its id and reads everything else from the
   * database, which is all a queued job will carry.
   */
  async run(turnId: string): Promise<TurnLog> {
    const turn = await TurnLog.findOrFail(turnId)

    if (turn.status !== 'pending') {
      throw new Error(`Turn ${turnId} is ${turn.status}: only a pending turn can be played.`)
    }

    /** Counted from here, when a worker picks the turn up — not from its submission. */
    const budget = new TurnBudget(this.#clock)
    const scene = await this.#loadScene(turn.sessionId)

    /**
     * Filled as the pipeline progresses, so a turn that dies halfway still
     * leaves behind everything it had managed to produce.
     */
    const trace = emptyTrace()

    try {
      const effects = await this.#runPipeline(turn, scene, trace, budget)

      await this.#complete(turn, scene, trace, effects)
    } catch (error) {
      /**
       * The log of a failed turn is what makes the failure debuggable at all,
       * so it is written before the error is re-thrown — and its own failure is
       * swallowed rather than allowed to mask the real one.
       */
      await this.#fail(turn, trace, error).catch(() => {})

      throw error
    }

    /** After the commit: the player is never told of a turn that could still roll back. */
    this.#events.emit(refOf(turn), { type: 'turn_completed', turn, character: scene.character })

    return turn
  }

  /**
   * Marks the turn failed and tells the player — unless it was already
   * settled, by the sweep most likely, which has told them already. Exactly one
   * terminal event per turn.
   */
  async #fail(turn: TurnLog, trace: TurnTrace, error: unknown): Promise<void> {
    const failure = await markFailed(turn.id, trace, error)

    if (failure) {
      this.#events.emit(refOf(turn), {
        type: 'turn_failed',
        failure: { code: failure.code, message: failure.message },
      })
    }
  }

  /** Returns the effects the model proposed, validated but not yet applied. */
  async #runPipeline(
    turn: TurnLog,
    scene: LoadedScene,
    trace: TurnTrace,
    budget: TurnBudget
  ): Promise<TurnEffects> {
    const context = buildContext(scene, turn.playerInput, turn.language)
    /** Read on every turn: from Phase 5 the list is the world's own. */
    const actionTypes = await actionTypesOf(THREE_MUSKETEERS)
    const meta: ValidationMeta = {
      actionTypes: actionTypes.map(({ actionType }) => actionType),
      npcHandles: scene.npcs.map(({ handle }) => handle),
      locations: uniqueLocationReferences(THREE_MUSKETEERS),
      locationArchetypes: locationArchetypeReferences(THREE_MUSKETEERS),
      npcDefinitions: npcReferences(THREE_MUSKETEERS),
      hitPointsMax: scene.character.hitPointsMax,
    }

    this.#events.emit(refOf(turn), { type: 'step_started', step: 'arbitration' })

    /**
     * It rules, and only rules: the outcome is staged by the narration step
     * whichever way it went. A refused output gets one more attempt; a
     * transport failure gets none.
     */
    const decision = await callStructured(
      this.#llm,
      {
        step: 'arbitration',
        systemPrompt: ARBITRATION_SYSTEM_PROMPT,
        userMessage: buildArbitrationMessage({ ...context, action_types: actionTypes }),
        jsonSchema: ARBITRATION_SCHEMA as unknown as Record<string, unknown>,
        validate: (payload) => validateArbitration(payload, meta),
      },
      { trace, budget }
    )
    trace.arbitration = decision

    const outcome = await this.#settle(turn, scene, decision, trace)

    const narration = await this.#narrate(
      turn,
      buildNarrationMessage({
        ...context,
        /** A verdict and a qualitative margin. Never the dice or the threshold. */
        outcome,
        intent_summary: decision.intent.summary,
      }),
      trace,
      budget
    )

    /**
     * Reads the narration already written: a refused output gets one more
     * attempt, which never reruns the narration.
     */
    return callStructured(
      this.#llm,
      {
        step: 'extraction',
        systemPrompt: EXTRACTION_SYSTEM_PROMPT,
        userMessage: buildExtractionMessage({ ...context, narration }),
        jsonSchema: EXTRACTION_SCHEMA as unknown as Record<string, unknown>,
        validate: (payload) => validateExtraction(payload, meta),
      },
      { trace, budget }
    )
  }

  /**
   * Free text, sent to the player fragment by fragment as it is written.
   * Nothing of it is stored until the turn completes: the fragments are
   * provisional, and the text persisted is exactly their concatenation.
   *
   * Free text, so there is nothing to validate and no second attempt: an
   * empty answer or a cut stream fails the turn like any transport failure.
   */
  async #narrate(
    turn: TurnLog,
    userMessage: string,
    trace: TurnTrace,
    budget: TurnBudget
  ): Promise<string> {
    this.#events.emit(refOf(turn), { type: 'step_started', step: 'narration' })

    const stream = this.#llm.streamText('narration', {
      systemPrompt: NARRATION_SYSTEM_PROMPT,
      userMessage,
      signal: budget.signalFor('narration', this.#llm.provider),
    })

    let narration = ''
    let next = await stream.next()

    while (!next.done) {
      narration += next.value
      this.#events.emit(refOf(turn), { type: 'narration_chunk', text: next.value })
      next = await stream.next()
    }

    recordCall(trace, next.value)
    trace.narration = narration

    return narration
  }

  /**
   * The outcome arbitration's ruling leads to. A roll is made by the backend
   * alone, on the skill `resolution_rules` ties to the chosen action type;
   * without a roll, the outcome was certain from the start.
   */
  async #settle(
    turn: TurnLog,
    scene: LoadedScene,
    decision: ArbitrationOutput,
    trace: TurnTrace
  ): Promise<OutcomeToNarrate> {
    const { mode, action_type: actionType, difficulty } = decision.resolution

    if (mode !== 'roll_required') {
      return {
        mode,
        result: mode === 'automatic_success' ? 'success' : 'failure',
        margin: null,
        reason: mode === 'narrative_automatic_failure' ? decision.validity.justification : null,
      }
    }

    const skill = await skillFor(THREE_MUSKETEERS, actionType!)
    /** A skill the character never learnt is rolled untrained. */
    const resolution = this.#rules.resolve(scene.character.skills[skill] ?? UNTRAINED, difficulty!)

    trace.roll = { skill, actionType: actionType!, ...resolution }

    this.#events.emit(refOf(turn), {
      type: 'roll_resolved',
      skill,
      ...toNarrationOutcome(resolution),
    })

    return { mode, ...toNarrationOutcome(resolution), reason: null }
  }

  /**
   * Ownership was checked when the turn was recorded: from here on, the turn
   * is all there is to go on.
   */
  async #loadScene(sessionId: string): Promise<LoadedScene> {
    const session = await Session.query()
      .where('id', sessionId)
      .preload('characters')
      .preload('worldState', (worldState) => worldState.preload('currentLocation'))
      .preload('locations', (locations) => locations.orderBy('createdAt', 'asc'))
      .firstOrFail()

    const character = session.characters[0]

    if (!character) {
      throw new Error(`Session ${sessionId} has no character to play.`)
    }

    /**
     * Completed turns only: a failed turn is not part of the story, and handing
     * the model an action that never happened would have it narrate around it.
     */
    const turns = await TurnLog.query()
      .where('sessionId', sessionId)
      .withScopes((scopes) => scopes.completed())
      .orderBy('turnNumber', 'desc')
      .limit(NARRATION_RECENT_TURNS)

    /** Only completed turns hold a number, so the highest one is the last of the story. */
    const last = await TurnLog.query()
      .where('sessionId', sessionId)
      .max('turn_number as max')
      .first()

    return {
      session,
      character,
      worldState: session.worldState,
      npcs: await presentNpcs(sessionId),
      /** Oldest first, so the model reads the exchange in the order it happened. */
      recentTurns: turns.reverse(),
      lastTurnNumber: Number(last?.$extras.max ?? 0),
    }
  }

  /**
   * State change and turn log land together: a state that moved without a log
   * entry explaining it would be impossible to reconstruct afterwards.
   *
   * The turn gets its number here, and only here: a number is a place in the
   * story, which a turn earns by completing.
   */
  async #complete(
    turn: TurnLog,
    scene: LoadedScene,
    trace: TurnTrace,
    effects: TurnEffects
  ): Promise<void> {
    const turnNumber = scene.lastTurnNumber + 1

    try {
      await db.transaction(async (trx) => {
        /**
         * Locked and re-read: the sweep may have expired this turn while the
         * model was answering. Its outcome is then settled, and must not be
         * overwritten — nor its effects applied.
         */
        const current = await TurnLog.query({ client: trx })
          .where('id', turn.id)
          .forUpdate()
          .firstOrFail()

        if (current.status !== 'pending') {
          throw new StaleTurnError(turn.id)
        }

        const applied = await applyDelta(
          {
            world: THREE_MUSKETEERS,
            sessionId: scene.session.id,
            character: scene.character,
            worldState: scene.worldState,
          },
          effects,
          trx
        )

        scene.session.lastActivityAt = DateTime.now()
        await scene.session.useTransaction(trx).save()

        turn.merge({
          ...traceColumns(trace),
          status: 'completed',
          turnNumber,
          /** As applied, which is what the player is shown — not as proposed. */
          appliedEffects: applied,
        })

        await turn.useTransaction(trx).save()
      })
    } catch (error) {
      /**
       * Another request reached this turn number first. The transaction rolled
       * back, so nothing of this turn was applied.
       */
      if (isTurnNumberConflict(error)) {
        throw new ConcurrentTurnError(turnNumber)
      }

      throw error
    }
  }
}

type LoadedScene = {
  session: Session
  character: Character
  worldState: WorldState
  npcs: PresentNpc[]
  /**
   * As many as the narrator reads, the longer of the two buffers; arbitration
   * keeps only the last of them.
   */
  recentTurns: TurnLog[]
  lastTurnNumber: number
}

function buildContext(
  scene: LoadedScene,
  playerInput: string,
  language: GameLanguage
): TurnContext {
  return {
    world: THREE_MUSKETEERS,
    character: {
      name: scene.character.name,
      hit_points: scene.character.hitPoints,
      hit_points_max: scene.character.hitPointsMax,
    },
    scene: {
      location: scene.worldState.currentLocation?.handle ?? null,
      npcs_present: scene.npcs,
      narrative_flags: scene.worldState.narrativeFlags,
      visited_locations: scene.session.locations.map((location) => location.handle),
      world_objects: scene.worldState.worldObjects,
    },
    recent_buffer: toRecentBuffer(scene.recentTurns),
    player_input: playerInput,
    language,
  }
}

function toRecentBuffer(turns: TurnLog[]): RecentTurn[] {
  return turns.flatMap((turn) => {
    const entries: RecentTurn[] = [{ role: 'player', text: turn.playerInput }]

    if (turn.narratedText) {
      entries.push({ role: 'narration', text: turn.narratedText })
    }

    return entries
  })
}

function refOf(turn: TurnLog): TurnRef {
  return { turnId: turn.id, sessionId: turn.sessionId, idempotencyKey: turn.idempotencyKey }
}
