/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Login: () => import('#controllers/login_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Turns: () => import('#controllers/turns_controller'),
}
