import type { Step } from '@/api/enums'
import type { Character, Roll, Turn } from './queries'

/**
 * A turn, front side: an explicit state machine (front spec, section 5.3.5).
 *
 * ```
 * idle ──submit──▶ submitting ──202──▶ in_progress ──turn_completed──▶ idle
 *                     │                   │   ▲
 *                     │                   │   └─ step_started / roll_resolved
 *                     │                   └──turn_failed──▶ failed ──retry──▶ submitting
 *                     └──network / 4xx / 5xx──▶ submit_failed ──retry──▶ submitting
 * ```
 *
 * Pure: it never generates a key, reads a clock or calls the API. The caller
 * hands it fresh keys and the answers it got, which is what makes it testable
 * without a browser or a backend.
 */

/** What the player asked for, and how the backend knows it. */
export type Submission = {
  playerInput: string
  /** Unknown for a turn picked up on reopening the screen: it was generated by an earlier visit. */
  idempotencyKey: string | null
  /** Unknown until the `202` — or an event carrying the key — names it. */
  turnId: string | null
}

export type Failure = { code: string; message: string }

export type TurnState =
  | { status: 'idle' }
  | { status: 'submitting'; submission: Submission }
  | { status: 'in_progress'; submission: Submission; step: Step | null; roll: Roll | null }
  | { status: 'failed'; submission: Submission; roll: Roll | null; failure: Failure }
  | {
      status: 'submit_failed'
      submission: Submission
      failure: Failure
      /**
       * `true` when the POST may never have reached the backend (network
       * error, 5xx): resending with the same key gets back the turn it may
       * have recorded, instead of playing a second one.
       */
      retryWithSameKey: boolean
    }

/** A turn event from the game's SSE channel (architecture, section 8bis). */
export type TurnMessage = { turnId: string; idempotencyKey: string | null } & (
  | { event: 'step_started'; step: Step }
  | ({ event: 'roll_resolved' } & Roll)
  | { event: 'turn_completed'; turn: Turn; character: Character }
  | { event: 'turn_failed'; failure: Failure }
)

export type TurnAction =
  /** The player sends a new action; `key` is a fresh idempotency key. */
  | { type: 'submit'; playerInput: string; key: string }
  /** The player asks to try again; `key` is used only if a new one is due. */
  | { type: 'retry'; key: string }
  /** The `202`, with the turn as it stands — pending, or already over on a repeated key. */
  | { type: 'accepted'; turn: Turn }
  | { type: 'submit_failed'; failure: Failure; retryWithSameKey: boolean }
  | { type: 'message'; message: TurnMessage }
  /** The turn read back: on reopening the screen, after a reconnection or a silence. */
  | { type: 'read'; turn: Turn }
  /** The player takes their text back to change it. */
  | { type: 'edit' }

export const initialTurnState: TurnState = { status: 'idle' }

/** Whether the input is locked: a turn is on its way. */
export function isBusy(state: TurnState): boolean {
  return state.status === 'submitting' || state.status === 'in_progress'
}

/** Changes whenever the turn in flight shows something new: the journal follows it. */
export function progressKey(state: TurnState): string {
  if (state.status !== 'in_progress') return state.status
  return [state.status, state.step, state.roll?.margin].join(':')
}

/**
 * Whether an event is about the turn in flight. It may arrive before the
 * `202`, so the key the front generated is matched as well as the turn id.
 */
export function concerns(state: TurnState, message: TurnMessage): boolean {
  if (state.status !== 'submitting' && state.status !== 'in_progress') return false

  const { turnId, idempotencyKey } = state.submission
  return (
    (turnId !== null && message.turnId === turnId) ||
    (idempotencyKey !== null && message.idempotencyKey === idempotencyKey)
  )
}

export function turnReducer(state: TurnState, action: TurnAction): TurnState {
  switch (action.type) {
    case 'submit':
      if (state.status !== 'idle') return state
      return {
        status: 'submitting',
        submission: { playerInput: action.playerInput, idempotencyKey: action.key, turnId: null },
      }

    case 'retry':
      if (state.status === 'failed') {
        // The failed turn is over and logged: trying again is a new submission.
        return {
          status: 'submitting',
          submission: {
            playerInput: state.submission.playerInput,
            idempotencyKey: action.key,
            turnId: null,
          },
        }
      }
      if (state.status === 'submit_failed') {
        return {
          status: 'submitting',
          submission: {
            playerInput: state.submission.playerInput,
            idempotencyKey: state.retryWithSameKey ? state.submission.idempotencyKey : action.key,
            turnId: null,
          },
        }
      }
      return state

    case 'accepted':
      if (state.status === 'submitting') {
        return settle(
          {
            status: 'in_progress',
            submission: { ...state.submission, turnId: action.turn.id },
            step: null,
            roll: null,
          },
          action.turn
        )
      }
      // An event carrying the key got here first: it only lacked the turn id.
      if (state.status === 'in_progress' && state.submission.turnId === null) {
        return { ...state, submission: { ...state.submission, turnId: action.turn.id } }
      }
      return state

    case 'submit_failed':
      if (state.status !== 'submitting') return state
      return {
        status: 'submit_failed',
        submission: state.submission,
        failure: action.failure,
        retryWithSameKey: action.retryWithSameKey,
      }

    case 'message':
      return onMessage(state, action.message)

    case 'read':
      if (state.status === 'idle' && action.turn.status === 'pending') {
        return {
          status: 'in_progress',
          submission: {
            playerInput: action.turn.playerInput,
            idempotencyKey: null,
            turnId: action.turn.id,
          },
          step: null,
          roll: action.turn.roll,
        }
      }
      if (state.status === 'in_progress' && state.submission.turnId === action.turn.id) {
        return settle(state, action.turn)
      }
      return state

    case 'edit':
      return state.status === 'failed' || state.status === 'submit_failed'
        ? initialTurnState
        : state
  }
}

function onMessage(state: TurnState, message: TurnMessage): TurnState {
  if (state.status !== 'submitting' && state.status !== 'in_progress') return state
  if (!concerns(state, message)) return state

  // Before the `202`, an event is as good an acknowledgement: the turn exists.
  const current =
    state.status === 'in_progress'
      ? state
      : {
          status: 'in_progress' as const,
          submission: { ...state.submission, turnId: message.turnId },
          step: null,
          roll: null,
        }

  switch (message.event) {
    case 'step_started':
      return { ...current, step: message.step }
    case 'roll_resolved':
      return {
        ...current,
        roll: { skill: message.skill, result: message.result, margin: message.margin },
      }
    case 'turn_completed':
      return initialTurnState
    case 'turn_failed':
      return {
        status: 'failed',
        submission: current.submission,
        roll: current.roll,
        failure: message.failure,
      }
  }
}

/** Applies a turn read back, or answered by the `202`, to the turn in flight. */
function settle(state: Extract<TurnState, { status: 'in_progress' }>, turn: Turn): TurnState {
  if (turn.status === 'completed') return initialTurnState

  if (turn.status === 'failed') {
    return {
      status: 'failed',
      submission: state.submission,
      roll: turn.roll ?? state.roll,
      failure: turn.failure ?? { code: 'unexpected', message: '' },
    }
  }

  return { ...state, roll: turn.roll ?? state.roll }
}
